### ISSUE TITLE
Texts centering in auth dialogs

### ISSUE THREAD

**Issue by madextreme** [modularcode/modular-admin-html#10]
In bootstrap4 ```text-center``` class was removed. 
We need to use new classes.

![2016-01-12_0114](https://cloud.githubusercontent.com/assets/3959008/12246847/46a5db6e-b8ca-11e5-8b33-9bf3d4fe1ea7.png)

**Comment by AramManukyan** [comment]
Done on develop branch
https://github.com/modularcode/modular-admin-html/commit/86e422fdd227cf2d8f33d77c66df2948efe2e275
