### ISSUE TITLE
I can't install

### ISSUE THREAD

**Issue by pepo-ec** [modularcode/modular-admin-html#107]
I'm trying to install ModularAdmin using the guide "Getting Started" but I have problems (log file)... I am using Kubuntu 8
[2018-06-29T22_54_24_164Z-debug.log](https://github.com/modularcode/modular-admin-html/files/2151156/2018-06-29T22_54_24_164Z-debug.log)

**Comment by krosoftware** [comment]
You can use this version (no install needed): https://github.com/modularcode/modular-admin-html/tree/gh-pages

**Comment by modularcoder** [comment]
This should be fixed
