### ISSUE TITLE
Logout link is wrong

### ISSUE THREAD

**Issue by madextreme** [modularcode/modular-admin-html#12]
On clicking logout you should be redirected to login page.

![2016-01-12_0120](https://cloud.githubusercontent.com/assets/3959008/12246931/c185493c-b8ca-11e5-8337-c21797eb7e46.png)

**Comment by AramManukyan** [comment]
Done on develoop branch
https://github.com/modularcode/modular-admin-html/commit/14710ea7a69362597a2c69afe1192923ba35b516
