### ISSUE TITLE
Design Items list Bulk actions

### ISSUE THREAD

**Issue by madextreme** [modularcode/modular-admin-html#13]
After selecting multiple items, we need to be able to make bulk operations, for example delete or mark as draft.

### Ideas

- Refer to wordpress editor's design, add dropdown near search dialog.

![2016-01-12_0123](https://cloud.githubusercontent.com/assets/3959008/12247011/522946aa-b8cb-11e5-8c2d-05d08907474a.png)

**Comment by Davidtiger92** [comment]
Wanted to place it near the items-search, but it doesn't worked properly. (chgidem xi trnum er title-block-i tak)

**Comment by AramManukyan** [comment]
@Davidtiger92 fixed
https://github.com/modularcode/modular-admin-html/commit/9f7977e3b765ea625cd9d3c848d3b7f626ca39c7

**Comment by madextreme** [comment]
@Davidtiger92  @AramManukyan  needs to be improved. We don't have bulk actions on mobile, so hide on mobile viewport.

**Comment by AramManukyan** [comment]
ah, ok
