### ISSUE TITLE
 Raphael is not defined, Only in index.html page others are fine.

### ISSUE THREAD

**Issue by IslamGad** [modularcode/modular-admin-html#17]
![image](https://cloud.githubusercontent.com/assets/6369399/15070578/5d32f342-1385-11e6-89bf-233152d28045.png)

**Comment by modularcoder** [comment]
@IslamGad Thanks for spotting. 
This started happening because Raphael.js library updated it's main file in bower.json
This is fixed now and new version 1.0.1 is released.

**Comment by IslamGad** [comment]
@modularcoder :+1: 
Great work, Very elegant admin panel by the way.

**Comment by modularcoder** [comment]
@IslamGad thanks for feedback! :)
