### ISSUE TITLE
Add sub-menu support to sidebar

### ISSUE THREAD

**Issue by modularcoder** [modularcode/modular-admin-html#18]
Would be nice to add sub-menu support to sidebar

**Comment by sauron918** [comment]
+1

**Comment by AramManukyan** [comment]
@modularcoder I have added it.
Please look.

![untitled](https://cloud.githubusercontent.com/assets/2745526/17348890/cc380e90-592a-11e6-9e08-0a28e0b66583.png)

[Add Sidebar Menu Levels](https://github.com/modularcode/modular-admin-html/commit/61846a5d39cfc0362f06c3cc9c7a5e02f8bff186)

**Comment by modularcoder** [comment]
@AramManukyan thx, will take a look soon.

P.S. moved commit to develop branch, until confirmed.

**Comment by AramManukyan** [comment]
ok

**Comment by harialby** [comment]
Hi,
I am using modular theme for my project.but the side menu not expanding and collapsing function not works for me.Anyone pls help me.
Thanks in advance
