### ISSUE TITLE
Implement gulp-sass-globe into app styles task

### ISSUE THREAD

**Issue by modularcoder** [modularcode/modular-admin-html#20]
Now all sass files are concatenated before SASS compilation.
Because of that when there is a syntax error in sass, It's hard to find the file causing it.

Using gulp-sass-globe instead of concatenation may solve this issue.

**Comment by modularcoder** [comment]
@ex37 axperutyun, sam naprosilsya :D

**Comment by ex37** [comment]
@modularcoder ha hastat, ban chasi :D

For this we need just one entry point SCSS file for the project, and for our case it's `_main.scss` 

Also I think we can add second entry point SCSS file to the project, like `vendor.scss` for including things like bootstrap, when creating custom builds. It will keep vendor specific css separated from user's css, but more importantly, it can dramatically decrease SCSS compilation times.

**Comment by modularcoder** [comment]
@ex37 let's start from _main.scss for now. 
The vendor style files are now processed via mainBowerFiles.

**Comment by ex37** [comment]
@modularcoder I was about cases you need custom build, say for Bootstrap or Font awesome
