### ISSUE TITLE
Question: How to send parameters to drawMorrisCharts function?

### ISSUE THREAD

**Issue by myn01** [modularcode/modular-admin-html#24]
How can I send the data array to drawMorrisCharts function from html or php page?
Then from app.js I would call drawMorrisCharts($data_array);
Thanks

**Comment by modularcoder** [comment]
@myn01 I think you can serialize  and print the array as a string and render it by PHP in some hidden input. After that parse the array by javascript, and pass to morris charts.

**Comment by modularcoder** [comment]
Or you may make AJAX calls, to get the data for charts.
