### ISSUE TITLE
Create a bower package

### ISSUE THREAD

**Issue by laravelish** [modularcode/modular-admin-html#26]

**Comment by modularcoder** [comment]
Hi @DeeJaVu 
Can you explain me please, what is the use case including the theme in bower? 
Because It's not a library, but a template.
Or I'm missing something?

Thanks

**Comment by DeeJaVu** [comment]
@modularcoder this for example has bower and npm to download the source easly instead of downloading a zip https://github.com/almasaeed2010/AdminLTE 

many people are using bower or npm it makes it easy to integrate it in to your project etc

**Comment by kdp8791** [comment]
Second this, would be nice if there was an easier way to integrate this into projects and keep up with updates vs. copying/pasting after changes are made.

**Comment by modularcoder** [comment]
@kdp8791 why not just add git remote and pull?
Because usually you use bower / npm for installing external libraries, and this is a theme.

**Comment by brucepc** [comment]
You can install as package as any bower/npm package simple like:
```npm install (--save-dev) https://github.com/modularcode/modular-admin-html.git```
or
```bower insall (--save-dev) https://github.com/modularcode/modular-admin-html.git```
and with some additional configuration into bower.json or package.json you can have what you want and use in your project

**Comment by Omnia-Code** [comment]
It would make sense to have a bower package for the stylesheets (sass or css).
I agree on @modularcoder that the whole theme as bower (or npm) wouldn't really be useful.

**Comment by modularcoder** [comment]
Closing this issue, since bower is now deprecated :)
