### ISSUE TITLE
Sparkline feature hardcoded to random values

### ISSUE THREAD

**Issue by DeveloperUniversity** [modularcode/modular-admin-html#27]
Hi, first off ... wow, awesome work.  Thank you so much for this!  I can't want to show you what I'm doing towards making it simple for ASP.NET MVC Core 1.0 developers to utilize this in real apps.  Spending this week on it.

Issue:

In app.js, lines 1108 to 1124, I would recommend somehow allowing developers to pass in data.  If the data is empty, THEN generate random data (lines 1112-1116).

As it stands right now, I'm not entirely sure how to expose the sparkline functionality to end-user-developers without editing any of the files in the /dist folder (which is where I'm choosing as the integration point with my Visual Studio solution so I can completely wipe out an older version of Modular Admin and paste your latest changes into without blowing away any code I've written.)

Any advice / workaround?

**Comment by DeveloperUniversity** [comment]
Actually, in app.js, lines 917 through 947 seem to do it correctly ... for the DASHBOARD version of the sparklines (whereas my original issue was in regards to the LIST PAGE version of the sparklines).

**Comment by modularcoder** [comment]
@DeveloperUniversity hi, thanks for your feedback.

The JS files of this version of modular admin are mostly for demo.
If you're trying to create other version like ASP you probably need to refer the sources, and create custom build environment.

**Comment by DeveloperUniversity** [comment]
Thank you.  Will do.
