### ISSUE TITLE
Only need one theme, so I need to modify/remove this code from app.js

### ISSUE THREAD

**Issue by krystyna93** [modularcode/modular-admin-html#33]
Hi,

I am modifying the layout to suit. 
However I have some code below that I dont know how to modify/remove it, because I dont think I need it if I just want one theme colour. 
If I stop it, the sidebar doesn't animate in/out and the Nprogress bar doesn't display.
Any thought will help me. 

Thanks.

	/************************************************
	*	Storage Functions
	*************************************************/
	function getThemeSettings() {
		var settings = (localStorage.getItem('themeSettings')) ? JSON.parse(localStorage.getItem('themeSettings')) : {};
		settings.headerPosition = settings.headerPosition || '';
		settings.sidebarPosition = settings.sidebarPosition || '';
		settings.footerPosition = settings.footerPosition || '';
		return settings;
	}
	function saveThemeSettings() {
		localStorage.setItem('themeSettings', JSON.stringify(themeSettings));
	}
});
$(function() {
	$("body").addClass("loaded");
});

**Comment by modularcoder** [comment]
All unused files needs to be removed from src/ folder, and admin should be recompiled.
