### ISSUE TITLE
Update to Bootstrap v4.0.0-alpha.5

### ISSUE THREAD

**Issue by jan-t3000** [modularcode/modular-admin-html#34]
To whom it may concern, I updated my local version to the current Bootstrap 4, didn't see any issues so far and it was quite simple.

Change line in **bower.json** to
`"bootstrap": "v4.0.0-alpha.5",`

and in **modular-admin-html/src/_common/_styles/layout.scss** replace 
`"$grid-gutter-width" with "$grid-gutter-width-base"`

Run _bower install_ again before _npm start_ and enjoy!

**Comment by modularcoder** [comment]
@jan-t3000 thanks, will update soon!

**Comment by modularcoder** [comment]
@jan-t3000 this is now done in 1.1.0 release, thanks
