### ISSUE TITLE
Cannot built app stylesheet

### ISSUE THREAD

**Issue by mehaase** [modularcode/modular-admin-html#36]
`app.scss` looks like it should be buildable, since it does not begin with an underscore, but:

```
$ sassc modular-admin/app/app.scss > app/app.css
sassc: error: Error: Undefined variable: "$sidebar-width".
        on line 4 of modular-admin/app/app.scss
>> 	padding-left: $sidebar-width;
   ---------------^
```

It seems like it should import `variables`, right?

If I add imports at the top of `app.scss`, then I can compile it stand-along:

```
@import '../variables';
@import '../../bootstrap/scss/variables';
@import '../../bootstrap/scss/mixins';
@import '../_common/_styles/mixins';
```

But since this is "modular" admin, I think each module should be capable of stand-alone build, right? Or did I misunderstand the meaning?

**Comment by mehaase** [comment]
Actually, the same is true of all the components, too, e.g. `alert`, `button`, etc. None of them can be built stand-alone, which limits the modularity of modular admin.

**Comment by modularcoder** [comment]
@mehaase well, because of some dependenices, the app.scss wasn't meant to be built stand alone.

please refer this task
https://github.com/modularcode/modular-admin-html/blob/master/build/tasks/app-styles.js

But any improvement ideas are welcome )

**Comment by mehaase** [comment]
Hey, I wanted to let you know that I started ported Modular Admin to Angular2Dart. In particular, I really focused on embracing web components and encapsulation, which means I've made heavy modifications to the original source. It's not feature-complete yet, but it's far enough to demonstrate the ideas: https://gitlab.com/hyperion-gray/ng2_modular_admin

Are you okay if I continue to call this Modular Admin, or would you prefer if I gave the project a new name? This Angular2Dart port will be released under the same MIT license and I have included your original copyright notice in the new project.

**Comment by modularcoder** [comment]
@mehaase Hey! Awesome work, thanks!
You may name it whatever you find suitable. 
As a suggestion maybe also add "dart" word in repo name to illustrate that it's build on dart, but It's absolutely up yo you :)

I would really appreciate if you'll give a link to the source project in the project description and also I would also be happy to refer your project in Modular Admin docs in "Other versions" section.

Best Regards
Gevorg

**Comment by mehaase** [comment]
Thanks, I will be sure to include a link as requested.
