### ISSUE TITLE
Modal backdrop

### ISSUE THREAD

**Issue by Bary92** [modularcode/modular-admin-html#39]
Hello, I used your module for the application I am creating at this time. My problem is on the modal box I use the jelix framework and the modal box is called via ajax, the box appears very well but when I click on the close button, the box disappears but there is always the page remains grayed out . Thank you in advance.
  Sorry for English.

**Comment by modularcoder** [comment]
Hi @Bary92 

You probably might need to check the modal component docs for Bootstrap v4.0.0-alpha.5.
https://v4-alpha.getbootstrap.com/getting-started/javascript/

Regards
Gevorg

**Comment by Bary92** [comment]
thank you!!! But the problem has not yet been resolved. I have the error display on the console
![capture](https://cloud.githubusercontent.com/assets/23556041/23199871/244819de-f8e2-11e6-8076-198d2acf376f.PNG)

**Comment by modularcoder** [comment]
@Bary92 seems like this error isn't related to modal. Seems like you removed some lib (probably nprogress), but admin tries to call a funtion from that plugin.

https://github.com/modularcode/modular-admin-html/blob/master/src/main.js

Could you please check app.js: line 1386 if you're using pre-built version?

Please let me know if that works

**Comment by Bary92** [comment]
The code you gave me is already in line 1386 of the app.js file. How do I know if the version I am using is a pre-built version? 
It does not work yet

**Comment by Bary92** [comment]
In the html tag of the index.html page, there is a class nprogress-busy

**Comment by modularcoder** [comment]
@Bary92 If you're not using gulp to rebuild the admin on any changes, then you're editing a single JS file, then you're using a prebuilt version. :)

Try to comment out those two lines.

```
// start load bar
NProgress.start();

// end loading bar 
NProgress.done();
```

**Comment by Bary92** [comment]
Thanks, but there is an error in the console and it does not work.
Can i edit the css files directly or do i have to create another css file for editing?
![capture1](https://cloud.githubusercontent.com/assets/23556041/23204178/8b99729a-f8f6-11e6-81b4-dcdccc4d4a13.PNG)

**Comment by modularcoder** [comment]
@Bary92 Seems you're missing some libs or elements. Unfortunately I can't help beyond that, because the errors are in the customized code.

**Comment by Bary92** [comment]
Thanks, I can edit the app.css file directly?

**Comment by modularcoder** [comment]
@Bary92 well, you can but it's not advised.
It's better to work on source code while running build-watcher, which will rebuld the project on every file change.

Please see this section
https://github.com/modularcode/modular-admin-html#development

Also be careful, the "dist/" folder would be removed on **every rebuld**.
