### ISSUE TITLE
Update bootstrap version to v4.0.0-alpha.6

### ISSUE THREAD

**Issue by modularcoder** [modularcode/modular-admin-html#42]
New version of bootstrap4 was released. v4.0.0-alpha.6
https://v4-alpha.getbootstrap.com/

Need to update modular-admin to latest version

**Comment by MikeChou** [comment]
v4.0.0-beta is around the corner, maybe just skip alpha6 and prepare for the beta?

**Comment by roxma** [comment]
Looking forward to this.

Looks like `alpha.6` adds some utilities that not availale in `alpha.5`. The `d-flex` with `justify-` and `align-` is really useful to me.

**Comment by modularcoder** [comment]
@roxma really out of time recently... Maybe you could do a Pull Request?

**Comment by modularcoder** [comment]
v1.2.0 released with Bootstrap 4 beta support

https://github.com/modularcode/modular-admin-html/issues/69
