### ISSUE TITLE
Side menu expand collapse not working

### ISSUE THREAD

**Issue by harialby** [modularcode/modular-admin-html#44]
Hi i am using modular theme and i am stuck this side menu.Side menu expand collapse functionality not working for me.When i click on a menu that has dropdown menus nothing happens.but demo page index.html working fine.Anyone plz help.

**Comment by modularcoder** [comment]
@harialby so If I'm not wrong you're trying to open files directly?

You need to run a local web-server on ```dist/``` directory.

See this section
https://github.com/modularcode/modular-admin-html#development

Please feel free to reopen the issue if this will not work.

Regards
Gevorg

**Comment by harialby** [comment]
Hi,
Thanks for your valuable reply.running a local web-server means running in local iis right? but i need this in my production environment .i am using the form as a master page so i copy the contents of form.html and took only the side menu and footer part for my layout page.still the menu not expanding and collapsing .Any suggestions will help me.i am new in this field .
Thanks in advance.

**Comment by modularcoder** [comment]
@harialby 
My guess is that you're missing metisMenu plugin in that case, which is responsible for sidebar menu collapsing/expanding.

Also please check your chrome console logs, to see what error do you get.

Regards
Gevorg

**Comment by duard** [comment]
I'm trying to implement this Template in my Angular-cli (4.0.1) application and the last thing I need is this menu ... it work some minutes ago but now it stop to work and I cant fix it anymore

**Comment by duard** [comment]
![screenshot from 2017-04-10 22-20-09](https://cloud.githubusercontent.com/assets/36894/24888765/edad48ac-1e3b-11e7-99a1-2784d728d7eb.png)

**Comment by duard** [comment]
:-) it works again now 

```
            "styles": [
                "../node_modules/font-awesome/css/font-awesome.css",
                "styles.css",
                "pokeball.css",
                "../node_modules/metismenu/dist/metisMenu.min.css"
            ],
            "scripts": [
                "../node_modules/jquery/dist/jquery.js",
                "../node_modules/tether/dist/js/tether.js",
                "../node_modules/bootstrap/dist/js/bootstrap.js",
                "assets/js/app.js",

                "../node_modules/metismenu/dist/metisMenu.min.js"
            ],
```

**Comment by duard** [comment]
Stop again :-/ 
![screenshot from 2017-04-10 22-40-17](https://cloud.githubusercontent.com/assets/36894/24889138/b3cebe92-1e3e-11e7-8f5f-4443a8d000b3.png)
