### ISSUE TITLE
Little style change

### ISSUE THREAD

**Issue by evreneter** [modularcode/modular-admin-html#48]
```
.card .card-header .title {
      color: #ffffff;
}
```
Seems more compatible with theme.

Thank you for your efforts.

**Comment by garbin** [comment]
If you want to contributing, I think you create a PR directly will be better. maintainer will review the PR, If the job is awesome, It will be merged.

**Comment by evreneter** [comment]
You are right. This is my first git experience. I will try to create PR. Thank you.

**Comment by modularcoder** [comment]
@evreneter  @garbin  appreciate it :)
