### ISSUE TITLE
Media library issue

### ISSUE THREAD

**Issue by brijeshborad** [modularcode/modular-admin-html#49]
Media library to choose image or upload image seems like not working. Images in library is not selectable and uploaded image is not showing in library. 

http://prntscr.com/f5r2sp

Thanks

**Comment by modularcoder** [comment]
@brijeshborad yes, you're right that part of functionality isn't implemented, and is done just as a concept.

Because feature requires customization, we decided to omit the implementation for now,

**Comment by brijeshborad** [comment]
Thanks @modularcoder 
But the concept is very nice because this type of feature is available in CMS like wordpress. Many developers want to implement this type of feature with other frameworks because it is very good one. 
I know it needs server side scripting to accomplish the implementation but we can use static images to complete this concept.

**Comment by modularcoder** [comment]
@brijeshborad I agree, but unfortunately currently I'm too short on time.
If you or someone could contribute to this feature it would be great :)

**Comment by brijeshborad** [comment]
@modularcoder Sure, I'll start work on it when i will have time as i am working on one project. :)
