### ISSUE TITLE
Demo pages should have links "download", "documentation", "view on GitHub".

### ISSUE THREAD

**Issue by madextreme** [modularcode/modular-admin-html#5]
Demo pages should have links "download", "documentation", "view on GitHub".
It's hard to navigate back to repository and/or download theme when you're viewing demo.

Need to design and implement additional links on all pages.

## Ideas

- Top bar under header

**Comment by Davidtiger92** [comment]
"Documentation" и "View on GitHub" разве это разные ссылки?

**Comment by madextreme** [comment]
Yep, you're right.
We have "Theme Docs" in sidebar, totally forgot about that.

But would be good to have "Download" + "View on Github" links, somewhere visible.

**Comment by Davidtiger92** [comment]
But what's the difference between "View on GitHub" and "Theme Docs". Aren't they have the same destination to https://github.com/modularcode/modular-admin-html ?

**Comment by madextreme** [comment]
Even now we have same docs and project urls, Docs refers exactly to documentation, while "View on GitHub" refers to the whole project on github.

**Comment by Davidtiger92** [comment]
Ok, if we're gonna separate them, then it's clear... thx

**Comment by madextreme** [comment]
It's not mandatory to separate them, just they are bit different conceptually :)

**Comment by madextreme** [comment]
@Davidtiger92 Ideally those linkes should be in header or under the header in separate panel.

**Comment by Davidtiger92** [comment]
yeah... need some help... can you log in fb or skype for a second?

**Comment by madextreme** [comment]
Merged to develop
