### ISSUE TITLE
NodeJS 8.x - not building/installing on this one

### ISSUE THREAD

**Issue by mart1n8891** [modularcode/modular-admin-html#54]
I couldn't get this project running using the latest version of NodeJS (8.1.2). Played around a bit, it kept throwing errors like "Python27 could not be found" (even though it's there) and "Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (57)" etc. I downgraded to NodeJS 6 LTS and tried it as well with NodeJS 7 and both worked perfectly fine, however. Once I upgrade to NodeJS 8 nothing works.

**Comment by mart1n8891** [comment]
Log:
[23:47:30] 'app-styles' errored after 20 ms
[23:47:30] Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports ( [...]\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> ( [...]\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> ( [...]\node_modules\gulp-sass\index.js:187:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! modular-admin-html@1.1.0 gulp: `gulp --gulpfile build/gulpfile.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the modular-admin-html@1.1.0 gulp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! [...]\npm-cache\_logs\2017-06-21T21_47_30_958Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! modular-admin-html@1.1.0 start: `npm run gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the modular-admin-html@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by modularcoder** [comment]
Hi @mart1n8891 
Thanks for report.

This is related to gulp-sass version. Is uses older node-sass version under the hood which doesn't support node8.

Will publish publish a new fix release soon.

Meanwhile here is what you can do to make it work on node 8

1. Update gulp-sass version from to ```"^3.1.0"``` in package.json
2. remove node_modules/ directory
3. run fresh ```npm install``` 

Please let me know if this solved your issue

**Comment by modularcoder** [comment]
@mart1n8891 new 1.1.1 release is published now.

Please let me know if this works

**Comment by mart1n8891** [comment]
Thank you for your quick reply! I can confirm that it works 👍

**Comment by bogdaniel** [comment]
Erm for me it seems that it doesn't work =D

**Comment by modularcoder** [comment]
@bogdaniel, could you provide more details, please?

node, nmp versions, error stack traces
