### ISSUE TITLE
Feature request: Dockerfile

### ISSUE THREAD

**Issue by japrogramer** [modularcode/modular-admin-html#55]
I would like to request  that a docker file be created so that me and many other people can get started quicker. This would help people who are not familiar with npm and would like to just get started with one simple command like

`docker built -t modular-admin .`

**Comment by japrogramer** [comment]
Also i cannot install bower globally for reasons. So you see a docker file would be so helpful.

**Comment by japrogramer** [comment]
I found a workaround by making a ubuntu chroot but this is really wasteful.

**Comment by modularcoder** [comment]
Hi @japrogramer 
Could you help me with that?
I'm not very experienced in docker.

**Comment by japrogramer** [comment]
I can't even get it setup without docker, from running it in a chroot ubuntu machine 
http://sprunge.us/gfNj

```
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> node-sass@4.5.3 install /home/n22/git/modular-admin-html/node_modules/node-sass
> node scripts/install.js

sh: 1: node: not found
modular-admin-html@1.1.1 /home/n22/git/modular-admin-html
+-- gulp-concat@2.6.1
| `-- concat-with-sourcemaps@1.0.4
|   `-- source-map@0.5.6 
+-- gulp-less@3.3.2
| +-- less@2.7.2
| | `-- source-map@0.5.6 
| `-- vinyl-sourcemaps-apply@0.2.1 
|   `-- source-map@0.5.6 
+-- gulp-uglify@1.5.4
| +-- uglify-js@2.6.4
| | `-- source-map@0.5.6 
| `-- vinyl-sourcemaps-apply@0.2.1 
`-- handlebars@4.0.10
  `-- uglify-js@2.8.29
    `-- source-map@0.5.6 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
npm ERR! Linux 3.18.0-14582-g2fa17b5c810f
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-sass@4.5.3 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@4.5.3 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/n22/git/modular-admin-html/npm-debug.log
```

**Comment by japrogramer** [comment]
here is more logs from npm-debug.log http://sprunge.us/IeAC

**Comment by ex37** [comment]
@japrogramer maybe you have installed node executable with an alias? Is `node -v` providing any output in your console?

**Comment by ex37** [comment]
@japrogramer this can be fixed by running installing https://launchpad.net/ubuntu/trusty/+package/nodejs-legacy
just run `sudo apt-get install nodejs-legacy`

**Comment by japrogramer** [comment]
cool, that fixed it. Im going write a Dockerfile so i can get it setup in other machines outside a traditional chroot. Ill make a pull request when i get it working.

**Comment by japrogramer** [comment]
@modularcoder I made a docker-compose setup for this project
[pull request]( https://github.com/modularcode/modular-admin-html/pull/57)

**Comment by modularcoder** [comment]
@japrogramer great, thank you!
I'll review and merge soon
