### ISSUE TITLE
Nested Sidebar Menu

### ISSUE THREAD

**Issue by jesephan** [modularcode/modular-admin-html#64]
Hi,

We are using this template with our project. It seems this template does not support nested menu? I tried it and the arrow right arrow no longer showing. 

Thanks

**Comment by modularcoder** [comment]
@jesephan doesn't support out of the box, but should be easy to add. 
Sidebar nav uses Metic menu plugin

**Comment by jesusephan** [comment]
okay thanks

**Comment by modularcoder** [comment]
This feature is now implemented in **v1.2.0**
