### ISSUE TITLE
connect-livereload doesn't work

### ISSUE THREAD

**Issue by codebude** [modularcode/modular-admin-html#67]
I checked out the lates codebase from Github but had to realize that indeed the live reload feature is activated in the gulpfile.js (`livereload: true`), but that it isn't working.

For my setup I could fix this, by appending all gulp tasks by the following code:
`.pipe(plugins.connect.reload());`

Example for app-pages.js-file:
Before:
```
// Output 
.pipe(gulp.dest(config.destDir)); 
```
After:
```
.pipe(gulp.dest(config.destDir)) 
.pipe(plugins.connect.reload()); 
```

If this is a general problem and not only for me, than I can send in a pull request, if wanted.

**Comment by modularcoder** [comment]
@codebude I think that's a common issue and a pull request would be kindly appreciated )

**Comment by codebude** [comment]
Added pullrequest over here: https://github.com/modularcode/modular-admin-html/pull/68
So this issue can be closed. ;-)
