### ISSUE TITLE
Open mobile/tablet menu on with swipe

### ISSUE THREAD

**Issue by modularcoder** [modularcode/modular-admin-html#7]
Open mobile/tablet menu on swiping from screen left edge.

**Comment by sauron918** [comment]
+1

**Comment by AramManukyan** [comment]
[Open mobile/tablet menu on with swipe](https://github.com/modularcode/modular-admin-html/commit/267722b7c4b83caf7a8eaddbcf6544b5b895c8e1)

**Comment by Omnia-Code** [comment]
Wouldn't it make more sense to detect touch capabilities with [modernizr](https://modernizr.com/) instead of relying on the device type mobile since there are also laptops with touch capabilities?
