### ISSUE TITLE
Small mobile view of items list broken

### ISSUE THREAD

**Issue by tilmanbremer** [modularcode/modular-admin-html#73]
I noticed that the items list is broken in the small mobile view since the update to bootstrap 4 beta. This seems to be a browser independent issue.

This is how it looks for me now:
![modular_admin_broken](https://user-images.githubusercontent.com/20415107/30071368-bd4cf014-9266-11e7-938f-0143cf9ad5cf.PNG)

This is how it used to look:
![modular_admin_before](https://user-images.githubusercontent.com/20415107/30071373-bf349d28-9266-11e7-987d-7ebbbb96c9bd.PNG)

**Comment by modularcoder** [comment]
@tilmanbremer big thanks for the report, haven't noticed this.

I'll apply the fix and will make a new release soon.

**Comment by modularcoder** [comment]
@tilmanbremer fixed now in the latest patch release

https://github.com/modularcode/modular-admin-html/releases/tag/v1.2.1

Thanks for reporting!
