### ISSUE TITLE
Sparkline charts hover labels are broken

### ISSUE THREAD

**Issue by madextreme** [modularcode/modular-admin-html#8]
Sparkline charts hover labels are broken

![2016-01-12_0105](https://cloud.githubusercontent.com/assets/3959008/12246602/d465f526-b8c8-11e5-9572-acb59c5a0657.png)

**Comment by AramManukyan** [comment]
Done

https://github.com/modularcode/modular-admin-html/commit/e10cb32e64a0025d94ebfc2a8d6eec2a8c48da68
