### ISSUE TITLE
about static yaml codes

### ISSUE THREAD

**Issue by mrtbst** [modularcode/modular-admin-html#80]
hi,

we have a user table and i need to show table values in a list on page.
I need to know how to get yaml data from ajax call in ***-page.hbs (i see its possible from file bu i need to read from database) or give datasource to list after ajax call.
Is there anyone to write correct way?

Thanks

**Comment by modularcoder** [comment]
Hi @mrtbst 
The yaml data files are mostly for tempting purposes.

For real-life usage you need to compile the template via providing the data (server side rendering) or make an AJAX request in JavaScript to your API (single page application).

**Comment by mrtbst** [comment]
thanks

**Comment by modularcoder** [comment]
👍
