### ISSUE TITLE
About modular admin port

### ISSUE THREAD

**Issue by mrtbst** [modularcode/modular-admin-html#81]
Hi everyone,
is there any way for change modularadmin listen port(4000) (nodejs) to 80 on Windows server. I know that 80 port is using by iis, is there any way to use both, if not i want to change iis port and is it possible for use 80  port by modularadmin(nodejs).
Thanks

**Comment by modularcoder** [comment]
@mrtbst  Hi

Sure, just update the port in the config file.
https://github.com/modularcode/modular-admin-html/blob/master/build/config.js#L9
