### ISSUE TITLE
Update bootstrap version to v4.0.0

### ISSUE THREAD

**Issue by modularcoder** [modularcode/modular-admin-html#82]
- [x] Migrate dependencies installation from bower to NPM
- [x] Update vendor libraries
- [x] Update bootstrap version
- [x] Remove bower deps
- [x] Update docs
- [x] Update cover image
- [x] Move `build/paths/` to `/config/paths` for better visibility
- [ ] Publish a new release

For the progress refer to this branch
https://github.com/modularcode/modular-admin-html/tree/v1-dev-bootstrap-version

**Comment by kirill-voronov** [comment]
Stable Bootstrap v4 has been released! https://blog.getbootstrap.com/2018/01/18/bootstrap-4/

**Comment by modularcoder** [comment]
Yep :)
@kirill-voronov BTW, much thanks for your donation!

**Comment by kirill-voronov** [comment]
You made a great product, unfortunately I cannot contribute but only make a small donations.
Please, I really want this update, I've tried to do so by my self but failed.
It also will be awesome (and required by bs4) to migrate project from bower.

**Comment by Mons-web** [comment]
Hello!
I am maybe naive, but isn't it just as simple as editing bower.json and running `bower install` to make the update ?

https://github.com/Mons-web/modular-admin-html/commit/4b20d13263db9faae1a4a7d3a1fd08b1b0c5aef0

And regarding moving to NPM, I guess we should just add bootstrap to package.json and update the paths, actually same thing for all the bower packages (I guess you could get rid of bower and use only npm)

**Comment by kirill-voronov** [comment]
Bower is deprecated now and bootstrap dropped supporting it since beta-2 http://getbootstrap.com/docs/4.0/migration/#beta-2-changes

I tried bower-away tool and ended up with kilometers of error messages I can't solve

**Comment by modularcoder** [comment]
Sorry guys, too busy on my primary work, haven't had a chance to work on this yet.

The thing is that for now a plugin called mainBowerFIles is used to obtain bower dependencies main files. In order to migrate from bower, the new dependencies should be installed by npm, and their paths should be manually defined in this file
https://github.com/modularcode/modular-admin-html/blob/master/build/paths/vendor.js

**Comment by modularcoder** [comment]
Ok, please follow this branch for updates.
https://github.com/modularcode/modular-admin-html/tree/v1-dev-bootstrap-version

Bower -> NPM migration seems like a boring work, so need to go one by one through all dependencies, and install them via npm
