### ISSUE TITLE
How to install additional HBS helpers ?

### ISSUE THREAD

**Issue by Mons-web** [modularcode/modular-admin-html#83]
Hi there!

Thanks for your work, I cloned your v1 repo and played a bit with it, it was my first gulp experience and it was very interesting :)

I would like to install a package to add additional handlebars helpers:
https://www.npmjs.com/package/handlebars-helpers

However, I didn't understand how to correctly install the package.
Basically, I would like to use those helpers in views (e.g. sorting an array before running a loop on it)
I tried to add `var helpers = require('handlebars-helpers')();` as mentioned in the doc, I'm not sure where to put it exactly, I've tried in several places (build/pages, src/main.js, etc) and this doesn't seem to work !

More generally, I didn't find a way to install and use any NPM package (unless gulp ones that I require directly in task files)

Any clue to help me finding how to get this working correctly ?

PS: I'm more a SASS/CSS guy than JS, I have few ideas to help you optimizing SASS code, for example by using Bootstrap stuff like $theme-colors array that would avoid repeating writing styles for each theme colors, I will try to contribute when I find some time for it :)

**Comment by modularcoder** [comment]
Hi @Mons-web 
The handlebars helpers are registered here
https://github.com/modularcode/modular-admin-html/blob/master/build/tasks/app-pages.js#L21

The helpers paths are registered as a glob here.
https://github.com/modularcode/modular-admin-html/blob/master/build/paths/app.js#L90

So to install new external helpers via npm, you need

1. install external helpers
2. define their paths in this file
https://github.com/modularcode/modular-admin-html/blob/master/build/paths/app.js#L90


Regards!  :)

**Comment by Mons-web** [comment]
Hi @modularcoder 
Thank you very much for your answer.
I could get helpers working!

This is how I did:

**1- install the helpers**
```
npm install --save handlebars-helpers
```

**2- update `app.js` with the new helpers path:**
```diff
   exports.helpers = [
     srcDir + "/**/*-helper.js",
     rootDir + '/node_modules/handlebars-layouts/index.js',
+    rootDir + '/node_modules/handlebars-helpers/index.js'
   ];
```

**3- Require 'handlebars-helpers' in `app-pages.js`**

I think that's where I was blocked, we have to write it in this specific way to not conflict with other HBS helpers that are already registered (Optionally pass your own handlebars) : 

```javascript
var helpers = require('handlebars-helpers')({
  handlebars: handlebars
});
```
